name: Deploy to Release Branch

on:
  workflow_dispatch:

permissions:
  contents: write  # Required to push to branches

jobs:
  deploy-to-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
      
      - name: Get current ref
        id: get_ref
        run: |
          echo "ref=${GITHUB_REF#refs/}" >> $GITHUB_OUTPUT
          echo "Running from: ${GITHUB_REF#refs/}"
      
      - name: Force update release branch
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Get tag name from current ref
          TAG_NAME=$(echo "${{ steps.get_ref.outputs.ref }}" | sed 's/tags\///')
          
          # Amend the last commit with tag name
          git commit --amend -m "Release: ${TAG_NAME}" --no-edit
          
          # Force push current commit to release branch
          git push origin HEAD:release --force
          echo "✅ Release branch updated to point to: ${{ steps.get_ref.outputs.ref }}"
          echo "✅ Commit message amended to: Release: ${TAG_NAME}"
      
      - name: Summary
        run: |
          echo "✅ Successfully updated release branch"
          echo "🚀 AWS Amplify will now deploy from the release branch"
          echo "📋 Current commit details:"
          git show --no-patch --format="Commit: %H%nAuthor: %an%nDate: %ad%nMessage: %s" HEAD